services:
  postgres:
    container_name: 'lonklink-postgres'
    image: 'postgres:17-alpine'
    env_file:
      - .env
    environment:
      POSTGRES_DB: 'lonklink'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 20s
      retries: 19
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data

  app:
    container_name: 'lonklink-app'
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    build:
      context: '.'
    ports:
        - "56655:8000"
    env_file:
      - .env
    init: true